export const ENV = {
    SES_SENDER_EMAIL: process.env.NEXT_PUBLIC_SES_SENDER_EMAIL,
    SES_RECEIVER_EMAIL: process.env.NEXT_PUBLIC_SES_RECEIVER_EMAIL,
    EMAIL_ACCESS_KEY: process.env.NEXT_PUBLIC_EMAIL_ACCESS_KEY,
    EMAIL_SECRET_KEY: process.env.NEXT_PUBLIC_EMAIL_SECRET_KEY,
    AWS_REGION: process.env.NEXT_PUBLIC_AWS_REGION,
  };
  